### ISSUE TITLE
Config Crash

### ISSUE THREAD

**Issue by aluunzui** [RayTrace082/untamedwilds#1]
**Describe the bug**
When editing configs minecraft crashes

**To Reproduce**
step 1: edit configs, disabling some creatures and some of the new features
step 2: open MC
step 3: crash

**Expected behavior**
minecraft should open and have the configs implemented.

**Screenshots**

**Additional context**
heres the [paste](https://pastebin.com/SSeiQTZ3)

**Comment by RayTrace082** [comment]
Seems like you forgot to install [Citadel](https://www.curseforge.com/minecraft/mc-mods/citadel)

If the issue persists, please post the new crashlog alongside your untamedwilds-common.json

**Comment by RayTrace082** [comment]
If the issue persists, post the new crashlog, alongside your untamedwilds-common.json config
