### ISSUE TITLE
SpawnEgss Error On Multiplayer Game

### ISSUE THREAD

**Issue by hu7x** [RayTrace082/untamedwilds#100]
**Describe the bug**
This mod Spawn Egg use exception

**Steps To Reproduce**
1.Create and Join a multiplayer game
2.Choose Spawn Egg,And use it
3.Console Print NullPointerException :( 
4.If use Turantula or Snake Egg,Will not spawn anything

**Crash Log**
https://pastebin.com/hYBnXNYK

**Screenshots**
None

**Version**
 - Minecraft version: 1.16.5
 - Version of the mod: 1.4.1
 - Additional mods: Untamedwilds,Citadel

**Other Info**
 - Test Server Core:forge-1.16.5-36.2.26
 - Java Version:11.0.9

**Comment by RayTrace082** [comment]
> untamedwilds:1.16.5-1.4.1

Update the mod to one of the more recent Alpha versions, this issue has been fixed there
