### ISSUE TITLE
i think the bear and big cat spawn eggs should be seperated again, it was much better that way

### ISSUE THREAD

**Issue by baddybadger5** [RayTrace082/untamedwilds#102]
*Before submitting a feature request, be warned, suggestions relating to version changes and/or additional mobs will be deleted. Please, delete this disclaimer before submitting a feature request*

**Is your feature request related to a problem? Please describe.**
i think the bear and big cat spawn eggs should be seperated again, it was much better that way 

**Describe the solution you'd like**
the reasoning because its very dumb and shouldnt have that feature. also when the spawn eggs were seperated it was better because you could get the animal you would like faster 

**Describe alternatives you've considered**

**Additional context**

**Comment by RayTrace082** [comment]
Not happening

It's meant to allow me (or anyone else) to add/remove variants without having to deal with a massive number of Spawn Eggs, and I love how convenient it is
