### ISSUE TITLE
Mobs can eat food thrown by players

### ISSUE THREAD

**Issue by SharkGuy123** [RayTrace082/untamedwilds#105]
*Before submitting a feature request, be warned, suggestions relating to version changes and/or additional mobs will be deleted. Please, delete this disclaimer before submitting a feature request*

**Is your feature request related to a problem? Please describe.**
If applicable, please provide a clear and concise description of what the problem is. 

**Describe the solution you'd like**
A clear and concise description of what you would like to happen.

**Describe alternatives you've considered**

**Additional context**

**Comment by RayTrace082** [comment]
This *should* already be a thing, at least for the mobs that do eat Items (if it's not properly working, consider it a bug)
