### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by DarkLordFG** [RayTrace082/untamedwilds#106]
![Screenshot_14](https://user-images.githubusercontent.com/101553587/158135735-3f942ad6-75a0-408c-aebe-ad721c29054c.png)
![Screenshot_15](https://user-images.githubusercontent.com/101553587/158135742-793ce1ff-9825-4496-9c38-38b360a4ef39.png)
I have this error I try yo create server how I fix that can you help me pls

**Comment by RayTrace082** [comment]
That's a really old version, update the mod to any of the 1.5.x versions
