### ISSUE TITLE
Updated 1.18.2 Version fails to load on server

### ISSUE THREAD

**Issue by Daihok41** [RayTrace082/untamedwilds#111]
**Describe the bug**
Updated 1.18.2 Version Falis to load on server. It does Load with game though. 

Here is the Crash report 
https://pastebin.com/DQEnWkjh

**Steps To Reproduce**
 Start Server, Server wont Load

**Crash Log**
If applicable, include a crash log through a text sharing service [eg. pastebin]

https://pastebin.com/DQEnWkjh

**Version (please complete the following information):**
 - Minecraft version: 1.18.2
 - Version of the mod: 1.18.2 - 2.1.0
 - Forge Version: 1.18.2 - 40.0.34
 - Additional mods: To many mods to List. Should list them in Crash Report.

**Comment by RayTrace082** [comment]
Fixed, will wait until tomorrow to see if any other game-breaking issues arise before releasing an update
