### ISSUE TITLE
cant tame any animals even babbies

### ISSUE THREAD

**Issue by jackowacko14** [RayTrace082/untamedwilds#114]
cant tame any animals even babbies newest version let me know why

**Comment by RayTrace082** [comment]
Just tested on 1.18.2, and it works correctly

Every variant has its own favorite food, [you can find them by digging through the .json files here](https://github.com/RayTrace082/untamedwilds/tree/1.16.3/src/main/resources/data/untamedwilds/entities), and only Mammals can be tamed (with the exceptions being Manatees, Hippos and Aardvarks)

As some caveats, using the wrong kind of food gives no feedback (I will probably add some particle effects if you give them the wrong food) and even if tamed, mobs will behave as they normally do (right-click with an empty hand to change their behavior between "Wander", "Sit" and "Follow/Protect")

**Comment by RayTrace082** [comment]
Found the bug, closing this issue for the better documented #118
