### ISSUE TITLE
I cannot tame any animals either im not sure whats the cause. I cant even feed them there favorite food.

### ISSUE THREAD

**Issue by SkinneyMcKinney** [RayTrace082/untamedwilds#117]
**Describe the bug**

**Steps To Reproduce**

**Crash Log**
If applicable, include a crash log through a text sharing service [eg. pastebin]

**Screenshots**

**Version (please complete the following information):**
 - Minecraft version: [e.g. 1.16.5]
 - Version of the mod: [e.g. 4.0.0]
 - Additional mods: [if the bug is the result of an interaction between mods]

**Comment by RayTrace082** [comment]
Duplicate
