### ISSUE TITLE
Can't Tame Mobs 1.16.5

### ISSUE THREAD

**Issue by aeddog** [RayTrace082/untamedwilds#118]
First- I see other people have reported this but I thought I would be more detailed to help more hopefully. 

Can't tame anything other than bears. I'm playing 1.16.5, and I'm using the foods that are said on the CurseForge description of the mod.

**Steps To Reproduce**
Tried to tame hyenas, rhinos, multiple species of big cats, and bears. All bear species worked, none of the others did.

**Version**
 - Minecraft version: 1.16.5
 - Version of the mod: untamedwilds-1.16.5-1.5.4.jar
 - Additional mods: I tried it on its own with JEI and Citadel and still had the issue.

**Comment by RayTrace082** [comment]
Welp, thank you for providing a replicable bug report

Turns out that during the 1.16 -> 1.18 transition, the function that checks if an item triggers breeding got it's name remapped into a different function

Should have a fix ready sometime soon

**Comment by aeddog** [comment]
Cool! Glad I could help. I really like this mod, I used to use DrZharks Mo Creatures a lot but I'm trying similar ones. This one has been my favourite I've found so far!
