### ISSUE TITLE
Sounds of Boars can be heard right next to the player despite them being several blocks away.

### ISSUE THREAD

**Issue by DigitalWendigo** [RayTrace082/untamedwilds#119]
**Describe the bug**
When near any wild boar, you'll hear the oink. But when you walk away from it, up to at most 20 or so blocks in all directions, the oinking is still heard as if it's right next to you and it's pretty loud.

**Steps To Reproduce**
1. Play minecraft 1.16.5, Untamed Wilds 1.14.1
2. Find a wild boar.
3. Walk near it to start the sound.
4. Walk away about 20 blocks, or tower up 20 blocks, or dig down 20 blocks and still hear it as if standing next to it. 

**Crash Log**
None. Doesn't crash.

**Screenshots**
None. 

**Version**
 - Minecraft version: 1.16.5
 - Version of the mod: 1.4.1
 - Additional mods: 
 Apple Skin-Forge 2.2.0
 Citadel -1.8.1
 Curios-Forge -4.0.8.2
 Dungeons Arise -2.1.49-beta
 Easy Villagers -1.0.13
 Enchanting Infuser -1.0.2
 Fast Leaf Decay -52.2
 Fast Suite -1.1.1
 Ferrite Core -2.1.0
 Get It Together Drops -1.1.1
 Gottsch Core -f36.2.0-1.1.1
 Gravestone -1.0.6
 Helium -1.0
 Immersive Engineering -5.0.7-143
 JEI -7.7.1.150
 Krypton Reforged -1.0.0
 Lazy Dfu -0.1.3
 Magnesium Extras -1.3.1
 Magnesium -1.5
 Ore Excavation -1.8.157
 Pam's Harvestcraft 2 Food Core -1.0.2
 Pam's Harvestcraft 2 Food Extended -1.0.4
 Pam's Harvestcraft 2 Crops -1.0.2
 Pam's Harvestcraft 2 Fruit Trees -1.0.1
 Placebo -4.6.1
 Puzzles Lib -1.0.15
 Radon -0.8.0a
 Raw Ore -3.0.2
 Reskillable -1.3.6
 Road Runner -1.4.1
 Simple Magnets -1.1.6
 Spartan Shields -2.1.2
 Supermartijn642 Config Lib -1.0.9
 Supermartijn642 Core Lib -1.0.16
 Swing Through Grass -1.5.3
 Terra Forged -0.2.15
 Toast Control 4.4.0
 Treasure 2 -1.7.3
 Untamed Wilds -1.4.1
 Waystones -7.6.4

**Comment by RayTrace082** [comment]
>Version of the mod: 1.4.1

Update to any of the alpha versions (1.5.X), this was fixed there a while ago
