### ISSUE TITLE
hello dev im having  problem with the new 1.2.0 version

### ISSUE THREAD

**Issue by mondoe3** [RayTrace082/untamedwilds#12]
the problem is that none of the new items or new spawn eggs are showing up even though i have the it in my mod folder do you know how i can fix this

**Comment by RayTrace082** [comment]
You are going to have to provide more information, because I can't do anything with that

Is Forge installed? Citadel? Are you launching the correct profile? Are you running any other mods? Is there anything strange in the logs?

**Comment by mondoe3** [comment]
sorry for the late response also sorry for creating a new issue thats my bad I dont know how to really use github heres all the mods i have installed 
![2021-06-14 (2)](https://user-images.githubusercontent.com/85883797/121987361-3167e380-cd4d-11eb-861d-0bf7adf0c8bd.png)

**Comment by RayTrace082** [comment]
There's doesn't seem to be anything wrong with your game if the rest of the mods are working

The only issue I see is that you are running 1.0.1 version of UntamedWilds, a pretty old one, the most recent version is 1.2.0 and you can get it [here, in CurseForge](https://www.curseforge.com/minecraft/mc-mods/untamedwilds/download/3350697), just delete the old file and drop the new one

**Comment by mondoe3** [comment]
mmk ive fixed the problem i had to delete the 1.1.0 version
