### ISSUE TITLE
Manatees just keep spawning

### ISSUE THREAD

**Issue by Mooge123** [RayTrace082/untamedwilds#120]
I know mobs are supposed to reproduce naturally but these sea potatoes seem to have found the secret to making a ton of themselves. They just keep growing and I cannot bring myself to purge them as they are just adorable, yet it is kind of getting out of hand. The world is not even that old, with just over an hour in the world/area.
There are as of writing this 255 of them, and I'm pretty sure they did not start out this way
![2022-04-07_21 49 46](https://user-images.githubusercontent.com/31638484/162347384-aeb93799-0463-4ea3-aa76-55bfb5a2932a.png)
![2022-04-07_21 26 48](https://user-images.githubusercontent.com/31638484/162347396-405da065-f9f6-46b3-be5e-f0476e08611c.png)

 - Minecraft version: 1.18.2
 - Version of the mod: 2.1.1

**Comment by RayTrace082** [comment]
What the fuck?

Yeah, while pretty funny, this is 100% unintentional and warrants a hotfix. Turns out that the sea potatoes are set to breed like Fish, and not like Mammals. Thank you for the report
