### ISSUE TITLE
Config Options to Disable Animals do not work

### ISSUE THREAD

**Issue by Peach774** [RayTrace082/untamedwilds#125]
**Describe the bug**
I have disabled boars and snakes but they still spawn in new worlds along with their associated features.

**Steps To Reproduce**
1. Disable a mob
2. Create a new world
3. The mob still spawns

**Version (please complete the following information):**
 - Minecraft version: 1.18.2
 - Version of the mod: 2.1.2

**Comment by RayTrace082** [comment]
Those config options are deprecated and will be completely gone soon™

The intended way to disable mobs is through a datapack

**Comment by RayTrace082** [comment]
Closing, since those configs don't exist anymore
