### ISSUE TITLE
**Crash on client when right clicking a mob with a item in hand**

### ISSUE THREAD

**Issue by Cataraxts** [RayTrace082/untamedwilds#126]
**Describe the bug**
Client crashes whenever a person right clicks a mob with any item in hand. Server is being utelized.

**Steps To Reproduce**
1. Walk up to a untamedwilds mob.
2. Right click on them.
3. Recieve crash report.

**Crash Log**
https://pastebin.com/cFbmCpKk

**Screenshots**
See crash report above.

**Version (please complete the following information):**
 - Minecraft version: 1.18.2
 - Version of the mod: 2.1.2
 - Additional mods: Listed on crash report.

**Comment by Daihok41** [comment]
Have gotten this same crash as well several times

**Comment by Naelim** [comment]
Any word on this? Continues to be a huge issue on servers

**Comment by r8420** [comment]
I'm having the same issue

**Comment by PAIIN2** [comment]
Is there a way to solve this issue? Has anyone found a fix?

**Comment by RayTrace082** [comment]
Just released a new version that **should** fix this issue

Will close the issue in a few days if everything seems to be good
