### ISSUE TITLE
How can i get love potion？

### ISSUE THREAD

**Issue by shaaaak** [RayTrace082/untamedwilds#129]
*Before submitting a feature request, be warned, suggestions relating to version changes and/or additional mobs will be deleted. Please, delete this disclaimer before submitting a feature request*

**Is your feature request related to a problem? Please describe.**
If applicable, please provide a clear and concise description of what the problem is. 

**Describe the solution you'd like**
A clear and concise description of what you would like to happen.

**Describe alternatives you've considered**

**Additional context**

**Comment by shaaaak** [comment]
hello？

**Comment by RayTrace082** [comment]
Debug item, not intended to be obtainable

Nothing stops you from adding a recipe for it through a datapack or CraftTweaker, however

**Comment by shaaaak** [comment]
thanks，i m really like that mod！
