### ISSUE TITLE
Blacklisting Dimensions

### ISSUE THREAD

**Issue by KeyesArc** [RayTrace082/untamedwilds#132]
We should be able to blacklist the mobs from this mod to spawn in specific dimensions..
I'm having a problem with this mod's mobs spawning all over my dimensions, and I wanna be able to blacklist those dimensions.  I didnt had this problem with any of my other mods, cause they all have a way to blacklist dimensions in the config files. yours kinda don't :/

**Comment by RayTrace082** [comment]
Just closing this issue since I have added this one indev, and will be released whenever I release a new update
