### ISSUE TITLE
Overload of sharks??

### ISSUE THREAD

**Issue by riverablue** [RayTrace082/untamedwilds#133]
While playing with friends on a server one of them notified me that sharks don't despawn & discovered an absurd amount of sharks in waters
![shaaarks](https://user-images.githubusercontent.com/82718561/163732443-2513401d-5aa0-4ff3-840e-d922d26d4e2f.PNG)
![sharkswtf](https://user-images.githubusercontent.com/82718561/163732376-bc8cc35c-6d3a-4c6e-9631-42141324ba26.PNG)

I suspect this may also contribute to the crashing of my server lolll I'm not upset its hilarious but I wanted to address it
 - Minecraft version: 1.18.1
 - Version of the mod: 2.0.0

**Comment by SharkGuy123** [comment]
Did u use betterfps distance mod?

**Comment by riverablue** [comment]
I may be using the better fps mod? I'd have to look again

**Comment by RayTrace082** [comment]
Can you share your untamedwilds-common Config file?

**Comment by DigitalWendigo** [comment]
I'm curious since I'm using the same mods, and am about to fully finish implementing untamed wilds into my private modpack. 
How does betterfps distance affect mob spawning?
