### ISSUE TITLE
STILL can´t Tame any Animal

### ISSUE THREAD

**Issue by Punkpikachu** [RayTrace082/untamedwilds#136]
**Describe the bug**
Must be annoying to get the same question over and over, but, can´t tame any baby animal still, even with,yey, their favourite food.

**Steps To Reproduce**
activate creative
spawn baby animal
give it favourite food
one time hearts show but then nothing happens

**Version
1.16.5 ver. 1.5.5

**Comment by RayTrace082** [comment]
Fixed
