### ISSUE TITLE
Tamed big cats don't sit or follow when right clicked -  untamedwilds-1.16.5-1.5.6

### ISSUE THREAD

**Issue by theyellowdin0** [RayTrace082/untamedwilds#137]
It's probably annoying to get another issue that have something to do with tamed mobs but tamed big cats don't follow commands.

I've tested this in a creative world and tamed big cats do attack the mob the player attacked but they don't follow or sit. Tamed rhinos, bisons and bears however do follow commands they can sit, follow, etg. But not big cats?

**Comment by RayTrace082** [comment]
Fixed, the function reached an NPE (in a Debug check for Creative mode) before the command change
