### ISSUE TITLE
1.18.1

### ISSUE THREAD

**Issue by Buckmenstar** [RayTrace082/untamedwilds#139]
Hey i really like the mod but i am playing on the 1.18.1 version and i know you said you wont support that version anymore but i was wondering if you could maybe fix a bug that doesnt let me tame anything except bears and also tamed big cats dont follow orders(i tamed them with the love potion in creative) i saw that you said that is a quick fix so i was wondering if you could do that or maybe let me know how to do it  (i also know you fixed it for 1.18.2 but i am playing on a server with my girlfriend and some of the other mods we have arent updated to that yet).

Thanks in advance.

**Comment by RayTrace082** [comment]
Apologies, but indeed I have no plans to update that version anymore

AFAIK, the issue with Big Cat orders can be bypassed by not being in Creative mode, and if you use CraftTweaker, you can add a recipe for the Love Potion item

**Comment by Buckmenstar** [comment]
OMG  that works!!! Thank you very much!!!
