### ISSUE TITLE
Big Cats names not being displayed properly when using Jade mod (HWYLA fork)

### ISSUE THREAD

**Issue by carlstrax** [RayTrace082/untamedwilds#143]
**Describe the bug**
The Big Cats' names are being displayed as "entity.untamedwilds.big_cat" when using the Jade Mod (HWYLA fork).
The other mobs are displaying their names fine like the Bears, etc.

**Steps To Reproduce**
1. Looking at a spawned Big Cat with the Jade mod installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/104706664/166621107-665a3427-8d22-4481-bfc3-b25f83a6a569.png)

**Version (please complete the following information):**
 - Minecraft version: [1.18.1]
 - Version of the mod: [untamedwilds-1.18.1-2.0.0.jar]
 - Additional mods: [Jade-1.18.1-4.4.1.jar]
 - Mod loader: [Forge]
 - Modloader version: [Forge: 39.1.2]

**Comment by AnasterianSunstrider** [comment]
It's the same for me as well.
