### ISSUE TITLE
Snake Hitbox

### ISSUE THREAD

**Issue by Tyrius1** [RayTrace082/untamedwilds#146]
Any chance you could increase the hitbox of the snakes a little bit? They feel a bit annoying to try to attack at the moment just because it's sort of hard to find their hitboxes.

**Comment by RayTrace082** [comment]
This is worth bringing up

At some point in the future, I would like to move some of the larger snakes (eg. Black Mamba) into their own larger class with a larger model, putting them between the small snakes and the large ones, which should make their hitboxes less stupid

That said, I have added a couple things for the next version to make snakes less annoying:
* Their aggression when stepped on is now pretty short (same with wake-up agression), so, unless you fight back, the snakes will just leave you alone after a couple bites
* I have made their hitboxes a bit bigger, but without limiting their ability to fit in 1x1 spaces
* Shovels can now OHK small snakes for the true outback experience

**Comment by Tyrius1** [comment]
Sweeet! Very nice :) I personally love the idea of dangerous snakes in the world and i'd love to see them infesting certain structures like jungle temples and desert pyramids!
