### ISSUE TITLE
Rhino and hyena taming/breeding item is air - untamedwilds-1.18.2-2.1.2

### ISSUE THREAD

**Issue by theyellowdin0** [RayTrace082/untamedwilds#148]
Tested on a creative world and the rhino and hyena taming item is air (empty hand)

Also tested this by going to survival mode and the taming item is still air.

Edit: I would also like to point out that on a server right clicking any mobs that you can't pick up from untamed wilds crashes the game (not the server)

**Comment by RayTrace082** [comment]
Should be fixed, feel free to reopen the issue if it persists
