### ISSUE TITLE
Config options

### ISSUE THREAD

**Issue by justin-slijkhuis** [RayTrace082/untamedwilds#15]
Hi there,
I don`t really have any bugs but I do have a request,
is it possible to add something in the config where it allows me to change where certain world gen is generated and how rare it is?

I have been working for a long time on a modpack and I actually do like the new generation. 
I am playing with byg and while adding reeds and bush sometimes makes it really beautiful, in some biomes it looks kinda bad.
I added a picture showing the Bayou biome from byg, I do like the reeds but it spawns way too often and it looks weird that it also spawns on grass, also I do not like that the bush spawns in this biome.
![2021-06-15_12 51 34](https://user-images.githubusercontent.com/84229234/122040716-7127dd00-cdd8-11eb-9211-caed05ea87d0.png)

I don`t want to sound bad because I really love the mod, especially the models for the animals are cool, maybe custom sounds when hit would be cool but that might be something for the future.
I really like that you add mobs that are not really in other mods with multiple styles.

I am really hoping that you could add config options for more customization!

**Comment by RayTrace082** [comment]
Adresed in the latest released version (1.2.1), exposed generation chance for the three Flora features (Reeds, Vegetation and Algae) and added a blacklist for disabling the features in specific biomes
