### ISSUE TITLE
MC crashed after rightclick event on entity

### ISSUE THREAD

**Issue by ghost** [RayTrace082/untamedwilds#150]
**Describe the bug**
MC crashes on interact with entity holding a block

**Steps To Reproduce**
Rightclick on an "Untamedwilds entity" with a block and the Server will crash

**Crash Log**
https://pastebin.com/dcUc6BRc

**Version:**
 - Minecraft version: [1.18.2]
 - Version of the mod: [untamedwilds-1.18.2-2.1.2]

**Comment by PAIIN2** [comment]
Is there a way to solve this issue? Has anyone found a fix?

**Comment by RayTrace082** [comment]
Duplicate of #126  (and fixed)
