### ISSUE TITLE
Game crashes upon right clicking any creature from untamed wilds

### ISSUE THREAD

**Issue by dorrek** [RayTrace082/untamedwilds#159]
**Describe the bug**
Every time you right click a creature the game saves and closes

**Steps To Reproduce**
Right click a creature with an empty hand or with something in it doesn't matter which

**Crash Log**
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "untamedwilds.util.EntityDataHolder.getFavouriteFood(int)" because the return value of "untamedwilds.entity.ComplexMob.getEntityData(net.minecraft.world.entity.EntityType)" is null
Exit Code: -1

this is the crash log
https://pastebin.com/UZ3XvCeN

**Screenshots**

**Version (please complete the following information):**
 - Minecraft version: 1.18.2
 - Version of the mod: 1.18.2-2.1.2
 - Additional mods: Medieval Minecraft v10

**Comment by theyellowdin0** [comment]
This was already fixed, via. untamedwilds-1.18.2-2.1.3.jar

https://www.curseforge.com/minecraft/mc-mods/untamedwilds/files/3794273

**Comment by RayTrace082** [comment]
What theyellowdin0 said, update the mod to fix it
