### ISSUE TITLE
Crash when shielding/attacking/taking damage

### ISSUE THREAD

**Issue by Dycilia** [RayTrace082/untamedwilds#160]
**Describe the bug**

**Steps To Reproduce**
1. Go to 'any untamed wilds animal'
2. Click on 'attack/defend'

**Crash Log**
If applicable, include a crash log through a text sharing service [eg. pastebin]

**Screenshots**
If applicable, add screenshots to help 
[crash-2022-05-25_19.33.58-client.txt](https://github.com/RayTrace082/untamedwilds/files/8773416/crash-2022-05-25_19.33.58-client.txt)
explain your problem.

**Version (please complete the following information):**
 - Minecraft version: [e.g. 1.16.5]
 - Version of the mod: [e.g. 4.0.0]
 - Additional mods: [if the bug is the result of an interaction between mods]
[crash-2022-05-25_19.45.32-client.txt](https://github.com/RayTrace082/untamedwilds/files/8773440/crash-2022-05-25_19.45.32-client.txt)

**Comment by RayTrace082** [comment]
Update the mod
