### ISSUE TITLE
Game crashes when rigthclick a mob

### ISSUE THREAD

**Issue by manuelmsni** [RayTrace082/untamedwilds#161]
**Describe the bug**
When I right click a mob [untamed wilds mod mob] with my bare hands or with any item the game crashes.

**Steps To Reproduce**
1. Right click on a mob [untamed wilds mod mob]

**Crash Log**
Error: java.lang.NullPointerException: Cannot invoke "untamedwilds.util.EntityDataHolder.getFavouriteFood(int)" because the return value of "untamedwilds.entity.ComplexMob.getEntityData(net.minecraft.world.entity.EntityType)" is null
Exit Code: -1

**Version (please complete the following information):**
 - Minecraft version: [1.18.2]
 - Version of the mod: [untamedwilds-1.18.2-2.1.2]
 - Version of forge: [40.0.54]

**Comment by RayTrace082** [comment]
Update
