### ISSUE TITLE
Big Cat Babies aren't Spawning

### ISSUE THREAD

**Issue by AlcatrazIsle** [RayTrace082/untamedwilds#162]
I'm not sure why, I've explored chunks and chunks and I haven't found a single big cat baby. I've found grown versions, but nothing else. It's the same for all the other animals.

**Comment by RayTrace082** [comment]
Intended, babies do not spawn naturally (currently)

**Comment by AlcatrazIsle** [comment]
> Intended, babies do not spawn naturally (currently)

Oh alright. Is there breeding or any way to tame big cats? Thank you.
