### ISSUE TITLE
Really small Hippo's [1.16.5 - 1.5.4]

### ISSUE THREAD

**Issue by loorikeet** [RayTrace082/untamedwilds#165]
**Describe the bug**
The hippo's have shrunk, I dont know what caused this because they used to be a normal size
when I spawn them in a seperate world they are the normal size

**Steps To Reproduce**
I have no idea

**Screenshots**
![2022-06-02_10 54 24](https://user-images.githubusercontent.com/59521717/171531377-ef54f85c-7333-4652-8524-fece3acd9171.png)

**Version (please complete the following information):**
 - Minecraft version: [1.16.5]
 - Version of the mod: [1.5.4]
 - Additional mods: 
![Screenshot 2022-06-02 120320](https://user-images.githubusercontent.com/59521717/171532004-e81dc561-1530-44c0-9946-402e3c88a045.png)

**Comment by loorikeet** [comment]
I created a backup of the world and went into creative and spawned a hippo is and the one I spawned is normal sized and the one I have is still really small
![2022-06-02_12 12 10](https://user-images.githubusercontent.com/59521717/171534112-c6b396ea-d891-44a7-8c7e-45d52f7bded8.png)

**Comment by RayTrace082** [comment]
Did you update the mod in an existing world from a (very) old version? because this will 100% happen if you do so
