### ISSUE TITLE
variant change not working

### ISSUE THREAD

**Issue by TuffCat** [RayTrace082/untamedwilds#168]
**Describe the bug**
shift right-clicking on a spawn egg just moves it to the top left corner of my inventory and then back to the bottom left. this is on creative mode, how the heck do i fix it???
**Steps To Reproduce**
1. make sure you're in creative mode.
2. get an untamed wilds spawn egg.
3. shift right-click on the egg while in the inventory.
4. it does not cycle through the variants.

**Version (please complete the following information):**
 - Minecraft version: 1.16.5
 - Version of the mod: 1.5.7
 - Additional mods: this mod is the only applicable one, the only other mods i have, add things, instead of changing basic minecraft features.

**Comment by RayTrace082** [comment]
You switch variants with the egg in your hand, not from the inventory GUI

**Comment by TuffCat** [comment]
ah, okay! thanks so much! (i am VERY new to this mod, sorry if i ask a lot of questions!)
