### ISSUE TITLE
Crash due to despawned damagesource?

### ISSUE THREAD

**Issue by HerringBarrel** [RayTrace082/untamedwilds#170]
Game crashed, stacktrace indicated it was due to a null return from net.minecraft.world.damagesource.EntityDamageSource.getSourcePosition()

I was testing out a villager mod, and after realizing that a zombie attack would interfere with that, I changed the difficulty to peaceful. The game crashed shortly thereafter. I suspect that something attacked a Bison, and then was despawned by peaceful mode before it called the method. 

I _did_ have a lot of other mods installed, but I don't think they caused the problem. Directly at least. I don't know if vanilla hostiles normally target bison.

Thank you for the lovely mod, anyways :)

**Mod Version**: 1.18.2 - 2.1.3

[**Crash Log**](https://pastebin.com/wPskHZEX)

**Comment by RayTrace082** [comment]
I forgot to add it to the changelog, but this issue should be now resolved
