### ISSUE TITLE
[1.18.2] No eggs

### ISSUE THREAD

**Issue by BlackAures1** [RayTrace082/untamedwilds#176]
**Describe the bug**
Spiders, snakes and other animals do not give eggs if the config is changed to more vanilla. After feeding, they just give 1 experience and no eggs.

**Steps To Reproduce**
1. Install this config
```
[gamerules]
	#Defines whether animals should breed without Player intervention.
	natural_breeding = true
	#Adds additional restrictions to mob breeding, including Biome/Temperature requirements and Overcrowding.
	hardcore_breeding = false
	#Pregnancy time is only used as a cooldown, babies pop out instantly like in Vanilla.
	easy_breeding = true
	#Whether breeding requires a Male and a Female to produce offspring/eggs. (Warning: may lead to uncontrolled spawns of eggs)
	gendered_breeding = true
	#Defines whether players can trigger breeding by feeding a creature's favourite item, like in vanilla.
	player_breeding = true
```
2. Create a large group of any animals (snakes or spiders) and try to breed them with his favorite food.
3. After a while you will be given 1 experience and no eggs. Even after 2-3 game days and in the right season the eggs do not appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/43911230/179812571-67c6f47d-3013-4550-9be9-f716804506bd.png)

**Version:**
 - Minecraft version: 1.18.2
 - Version of the mod: untamedwilds-1.18.2-2.1.3
 - Additional mods: The whole list of mods is in the previous report, if you need it here.

**Comment by BlackAures1** [comment]
Checked the reproduction with the standard config. That doesn't work either.

**Comment by RayTrace082** [comment]
Fixed for the next version

**Comment by BlackAures1** [comment]
When will this patch be approximately? ^^

**Comment by RayTrace082** [comment]
This issue should be fixed, mobs do lay eggs with the provided configs. Will close the issue in a few days if no further issues are reported
