### ISSUE TITLE
untamed wilds has failed to load correctly

### ISSUE THREAD

**Issue by tmarva** [RayTrace082/untamedwilds#177]
when i open the game it doesnt loads correctly
![image](https://user-images.githubusercontent.com/109828446/180571402-97458465-54f9-4793-a3ac-8688bc357cf4.png)
[crash-2022-07-22_18.21.21-fml.txt](https://github.com/RayTrace082/untamedwilds/files/9172261/crash-2022-07-22_18.21.21-fml.txt)

**Version (please complete the following information):**
 - Minecraft version: 1.18.2 forge-40.1.68
 - Version of the mod: untamedwilds-1.16.5-1.5.8

**Comment by RayTrace082** [comment]
>Minecraft version: 1.18.2
>Version of the mod: 1.16.5

🤔
