### ISSUE TITLE
Dupe leashes

### ISSUE THREAD

**Issue by BlackAures1** [RayTrace082/untamedwilds#179]
**Describe the bug**
You can get an infinite number of leashes with crates.

**Steps To Reproduce**
1. Tie the sheep with a leash and throw it in an open box.
2. The box will close and 1 leash will drop out
3. Open the box and the sheep will be leashed (+1 leash).

**Version (please complete the following information):**
Minecraft version: 1.18.2
Version of the mod: untamedwilds-1.18.2-2.1.3

**Comment by BlackAures1** [comment]
There is also another little visual bug with the box. One of the sides disappears if you move a small distance away from the box, but I think you know about this bug.

**Comment by RayTrace082** [comment]
Leash duplication fixed, and yeah, multi-block models are pretty janky, but I still think the instances where it works are worth the occasional jank
