### ISSUE TITLE
Tetra compatibility: Any item is "Pearl+" modifier

### ISSUE THREAD

**Issue by copygirl** [RayTrace082/untamedwilds#180]
### Description
When modifying a Tetra tool, any item is valid in the socket slot as a "Pearl+" modifier.

### Steps To Reproduce
- Get a Tetra workbench and hammer.
- Edit the socket upgrade slot.
- Notice that any item is applicable.  
  (Even empty slots are highlighted as if valid.)

### Comments
I looked at how [tetra does things](https://github.com/mickelus/tetra/blob/1.18/src/main/resources/data/tetra/schematics/single/socket.json) and maybe the format changed during an update and now `"material": { "item": "untamedwilds:material_pearl" }` would need to be changed to `"material": { "items": [ "untamedwilds:material_pearl" ] }`. Just a guess. I could not confirm because the way Tetra loads its datapack stuff doesn't allow me to override your additions (from what I can see, anyway). Unfortunately, this also means my modpack has this issue with no way to fix it, without removing your mod, unless I'm willing to modify and redistribute the mod's `.jar` file.

Also, is it just me or is the repository outdated?

### Screenshot
![image](https://user-images.githubusercontent.com/272586/181700295-beffc1aa-8342-4b53-b9e9-89f50d6c718c.png)

### Versions
- Minecraft: `1.18.2`
- Untamed Wilds: `2.1.3`
- Tetra: `4.9.3`

**Comment by RayTrace082** [comment]
The fix for this issue had been provided a few days ago by a contributor (Unkownn66) and will be released with the next version
That's pretty much what happened, Tetra changed a bit the formatting in the 1.16 -> 1.18 migration, and I didn't find it out until very recently

For what it is worth, removing the tetra folder from inside the .jar's data folder will fix the issue, and I am okay with the .jar file being redistributed when it comes to bug fixing

**Comment by copygirl** [comment]
We can probably wait for an update. Hoping it will come out within the next week or two.

Do you mind me asking why the repository is outdated?
As a modpack author I like using source code to look up certain things, when it's available.

**Comment by RayTrace082** [comment]
The main reason is that I changed workspace to keep the 1.16 and 1.18 codebases separate, and I originally forgot to push the 1.18 project into its own branch, after that, it's mostly a mix of:
- WIP content I have been working on for a long while, that I do not want to spoil
- Lack of time/interest in modding/minecraft (no plans on quitting for a while, but progress has been quite slow)
- Most data of interest for users can be found in the non-obfuscated data files

This should be a good reminder to publish the source code once I am finished with the update, however

**Comment by RayTrace082** [comment]
Fixed
