### ISSUE TITLE
1.18.2 client crash on right clicking any mob from this mod

### ISSUE THREAD

**Issue by FrAndromede** [RayTrace082/untamedwilds#181]
**Describe the bug**
Using Forge. Right clicking on a mob from this mod will immediately crash the client.

**Steps To Reproduce**
Right click on any mob from this game. It will check the mob's favourite food and crash the client (at least, for me).

**Crash Log**
(https://pastebin.com/p4gvTKaT)

**Screenshots**

**Version (please complete the following information):**
 - Minecraft version: 1.18.2 (Forge)
 - Version of the mod: untamedwilds-1.18.2-2.1.2.jar
 - Additional mods: Not sure, it's part of the modpack Medieval Minecraft for Forge 1.18.2

**Comment by FrAndromede** [comment]
Setting player_breeding to true in the untamedwilds-common.toml file (located in the server's config folder) seems to fix the problem, at least until the bug is fixed. Right-clicking on a tortoise, for example (this has been tried with other animals) with a sword no longer causes a crash.

**Comment by RayTrace082** [comment]
>Version of the mod: untamedwilds-1.18.2-2.1.2.jar

[Update the mod](https://www.curseforge.com/minecraft/mc-mods/untamedwilds/files/3794273), there's a newer version that fixes that problem
