### ISSUE TITLE
animals appear on the trees minecraft 1.16.5

### ISSUE THREAD

**Issue by DragonAstemirN** [RayTrace082/untamedwilds#183]
animals spawn in the treetops

and noticed this problem with the dynamic trees mod
problem detected only with large animals, not burrows

![2022-08-05_19 50 36](https://user-images.githubusercontent.com/94336869/183229264-e284b07c-452e-4299-99af-63be3e1233ff.png)
![2022-08-05_19 50 43](https://user-images.githubusercontent.com/94336869/183229319-166f6b02-7927-43bb-9c74-76bba3847c17.png)

 - Minecraft version: [ 1.16.5]
 - Version of the mod: [ 1.5.7]
 - Additional mods: [dynamic trees mod]

**Comment by RayTrace082** [comment]
Sorry, 1.16 is not supported anymore
It's fixed in 1.18
