### ISSUE TITLE
Big Cats in Cages All Labeled as Cave Lions!?

### ISSUE THREAD

**Issue by bigfoot102030** [RayTrace082/untamedwilds#184]
I was playing with this mod in survival earlier, and I noticed after capturing a Leopard with a cage trap that it was called a Cave Lion instead. I went to creative to further test out this potential bug, and found that ALL big cats in cage traps are called Cave Lions. The genders are correct, but the species is not.

(I don't know how to upload screenshots, but I assume the issue won't be difficult to recreate!)

1.18.2
Version 2.2.0

**Comment by bigfoot102030** [comment]
After further investigation, I have discovered that all species of Hyena are called Aardwolf when in cages... will keep testing this. Also I have discovered that news have no favorite food in the patchouli guide book! And all of the foods are displayed as their item tags as opposed to the name of the item themselves.

**Comment by bigfoot102030** [comment]
I have continued my discoveries, and I have found that it applies to any species with variations. For example, I captured an Indian Rhinoceros with a cage, and the item displayed as a Black Rhino when I hovered over it. I believe it always displays the variant number 0!

**Comment by Neverl0re** [comment]
I've been collecting animals on a server with my friends, And I have a trio of Reticulated Pythons and one Green Anaconda...But they all show up as Green Anaconda inside their cage traps. ": P I think you're right.

**Comment by RayTrace082** [comment]
Fixed in my end, to be released in the future

Basically, the tooltip was looking for a different NBT tag, and since nothing could be found, it defaulted to the first defined variant

It's a purely visual bug, all NBT data is correctly preserved, so your mobs are all safe
