### ISSUE TITLE
Fishing

### ISSUE THREAD

**Issue by MinecraftPerson** [RayTrace082/untamedwilds#188]
I think it would be cool if you added some kind of fishing to your mod. I know there's chum (and my favorite advancement that comes with it), but what it you could put it on a hook, and fish for mobs like trevally, catfish, triggerfish, arowana, football fish, and just maybe a turtle! I think it would be cool to watch a fish entity bite the line so you can reel it in, which is something I've been looking for in a mod for a while, especially one with high quality models like these. Just maybe you could even add more things to use as bait like worms, leeches, and possibly fake baits like a Mister Twister, just a suggestion, this is all just a suggestion, I guess. but that's just an idea.

**Comment by RayTrace082** [comment]
As cool as it would be, it sounds like an absolute nightmare to code, especially when it comes to handling compatibility
If any other mod does it, I'd very much rather add compatibility with it
