### ISSUE TITLE
Bug Collection: mobs give birth to adult mobs, not babies, some big cats always sleep, some never sleep.

### ISSUE THREAD

**Issue by IceaPlayzPC** [RayTrace082/untamedwilds#2]
A collection of three bugs in one report to reduce spam

Issue 1: Mobs give birth to adult mobs and not actual babies
**Describe the bug**
When you breed a mob (big cats confirmed, i haven't tested the other mobs but this happened with two big cat species), when it comes time to give birth, a full grown cub pops out instead of a baby. The only way to get a baby mob is to right click the mob with the respective spawn egg

**To Reproduce**
breed two mobs together
if easy breeding is off, wait for the timer to run out

**Expected behavior**
I expected the mobs to give birth to babies, not pop out full adults

**Screenshots**
Github wouldn't let me upload the screenshot i had unfortunately. It just loaded infinitely

**Additional context**
n/a

Issue 2: some big cats always sleep while some never sleep at all

A collection of three bugs in one report to reduce spam

Issue 1: Mobs give birth to adult mobs and not actual babies
**Describe the bug**
While playing around with the big cats, i noticed that some go to sleep and never wake back up unless hungry and near a mob or if hit, while others just never slept at all. The Jaguar would sleep infinitely, and i assume tigers and mountain lions do so too by how fast they fall asleep. Snow leopards, however, never sleep.

**To Reproduce**
-Spawn a big cat
-Observe its behaviour

**Expected behavior**
I'm assuming all big cats are supposed to nap periodically, or sleep during the day, but then wake back up and be active at night.

**Screenshots**
as said above, github won't let me upload a screenshot thus softlocking me to this page

**Additional context**
n/a

Apologies if i'm not supposed to cram 2 bugs in one report, if i'm not allowed to i can re-post this as two separate reports.
Thanks for reading! This mod is amazing btw. I haven't tested all the mobs so if i find issues with them that's similar to the bugs here i'll update this with any info i get

**Comment by RayTrace082** [comment]
Thanks for the reports. I'm fine with squeezing multiple bugs in one post, provided they are minor

Oof, this first one was really, really stupid, it's now fixed on the upcoming version

Sleep behaviors have been a massive thorn on this project, and I think disabling them altogether is a sensible choice until they get a complete cleanup. That said, I have not been able to replicate the issue, Big Cats seem to sleep when they are meant to, at preset times of the day (do keep in mind each Big Cat has it's own individual sleep schedule, loosely based on their real counterparts, and that they also require some sort of shelter to claim as a sleeping spot, which means that Snow Leopards very rarely find a safe place to sleep at all)

Leaving the issue open, just in case you have any more news on the sleep schedules

**Comment by RayTrace082** [comment]
Sleep behaviors got cleaned up as part of the latest update, closing this issue
