### ISSUE TITLE
A lot of animals, like bisons, rhinos, hippos, aardvarks, camels and hyenas, don't breed naturally

### ISSUE THREAD

**Issue by ALittleGhazt** [RayTrace082/untamedwilds#203]
**Describe the bug**
A lot of animais, like bisons, rhinos, hippos, aardvarks, camels and hyenas, don't breed naturally, but the big cats, bears and boars breed naturally

**Steps To Reproduce**
1.put two identical animals I mentioned in a pen, one male and one female
2. Place water and food near them.
3. use the analyzer to see if they are in a suitable mate period
4. this worked for bears, big cats and wild boars, but it didn't work for the creatures I mentioned.

**Screenshots**

**Version (please complete the following information):**
 - Minecraft version: [e.g. 1.18.2]
 - Version of the mod: [e.g. 2.2.0]

**Comment by RayTrace082** [comment]
Should be fixed in the latest version 2.3.0, will leave the issue open just in case

**Comment by ALittleGhazt** [comment]
when will version 2.3.0 be released??

**Comment by ALittleGhazt** [comment]
> Should be fixed in the latest version 2.3.0, will leave the issue open just in case

does that mean it was fixed?

**Comment by ALittleGhazt** [comment]
> 

are you sure they are breeding naturally?

**Comment by ALittleGhazt** [comment]
> Should be fixed in the latest version 2.3.0, will leave the issue open just in case

are you sure they are breeding naturally? are you sure they are breeding naturally? Because I just tested it and it didn't work
