### ISSUE TITLE
Small animals not spawning, but burrows there

### ISSUE THREAD

**Issue by PillowGF** [RayTrace082/untamedwilds#212]
I've recently started playing with Untamed wilds, and all the big animals and fish are spawning, but anything that lives in a burrow is not.

**Comment by RayTrace082** [comment]
By default, small animals do not spawn in the world, only Burrows do (which do slowly spawn X small animals)

You can change that in the config so the small animals spawn directly instead

**Comment by Joel1234545** [comment]
I tried disabling it and it still adds burrows?
