### ISSUE TITLE
I think blue whales should be bigger

### ISSUE THREAD

**Issue by AquaticFlapper** [RayTrace082/untamedwilds#213]
Not sure if these types of suggestions are allowed I know species requests aren’t but I think blue whales should be bigger. They are smaller than the Alex Mob’ cachalot/sperm whale and pretty small for a blue whale in Minecraft. I’d prefer them to be a little bigger. But it’s fine if you disagree and don’t add it. Sorry if this is a invalid suggestion.

**Comment by BadAtCoding17** [comment]
Not sure if the mod author would make them much larger, as super large mobs in minecraft can have difficulties with accurate hitboxes or pathfinding. That being said, this mod allows mob sizes to be changed with datapacks, so here's one I threw together in 30 seconds that makes blue whales a little bigger.

[LargerBlueWhales.zip](https://github.com/RayTrace082/untamedwilds/files/11327211/LargerBlueWhales.zip)

**Comment by RayTrace082** [comment]
Not going to make them bigger, unless there's a non-awful way to dynamically resize hitboxes

Not to mention how their visual scale can be easily changed with datapacks, as @BadAtCoding17 did
