### ISSUE TITLE
Add SnailFish

### ISSUE THREAD

**Issue by TitanosaurLockedMilkyWayMilkyWay** [RayTrace082/untamedwilds#218]
Add SnailFish A Rare Fish And Also The Deepest Living Fish That Man Has Ever Known They Have A Transparent And Clear Body People Call It SnailFish They Bring Beauty To The Deep Ocean In Minecraft.
![27566_4x3](https://user-images.githubusercontent.com/130964987/233074509-d0b490b2-f09b-4a76-9aa1-3117a7994937.jpg)

**Comment by RayTrace082** [comment]
Not taking mob suggestions
