### ISSUE TITLE
Rhinocerus and Hippo play cow sounds 1.18.2

### ISSUE THREAD

**Issue by xFirefalconx** [RayTrace082/untamedwilds#222]
Hi, I've recently ran across a bunch of mobs that might just be using the snorting noise of cows, but the problem seems to be that other cow sounds get played, as well, which is very... immersion breaking. 
Rhinocerus and the hippo do this definitely. I wonder if this can be changed so they sound more like their natural selves.

**Comment by RayTrace082** [comment]
Not a bug. You can use a datapack to change their sounds into any sound asset loaded by Minecraft

I'd love to add better sounds for both those mobs, however, I do not have access to royalty-free, license-compatible sound assets, nor to the combination of wild Rhinoceros + professional-grade recording equipment, so they are staying as Cows for the foreseeable future
