### ISSUE TITLE
Whales are invisible? Whale sharks aren't but whales I can hear them but they are completely invisible?

### ISSUE THREAD

**Issue by Bleeful** [RayTrace082/untamedwilds#227]
I don't know how to fix it, ive tried to spawn whales but they are just invisible, i can still here them but cant see them? Whale sharks still work though? Thanks :)

**Comment by RayTrace082** [comment]
Summon command or spawn egg? 

You need to explicitly define "Size: 1" NBT when summoning whales via commands. Spawn eggs work fine
