### ISSUE TITLE
Various land mobs sometime spawn in the water as well with this mod? Also Datapack does not work with this mod?

### ISSUE THREAD

**Issue by lSherozl** [RayTrace082/untamedwilds#235]
Why is there a random rhino in the ocean

<img width="1071" alt="image" src="https://github.com/RayTrace082/untamedwilds/assets/65663746/5765fe0f-badd-4ca8-ad39-ae3653390b12">

**Comment by lSherozl** [comment]
I created this straightforward Data pack 
<img width="460" alt="image" src="https://github.com/RayTrace082/untamedwilds/assets/65663746/20dc3bd6-8497-42f6-b71b-b6741e73d2a3">
<img width="570" alt="image" src="https://github.com/RayTrace082/untamedwilds/assets/65663746/e817a861-abdd-4950-914c-93a60b0c58be">
<img width="947" alt="image" src="https://github.com/RayTrace082/untamedwilds/assets/65663746/13894a7d-eae1-4d69-9e6e-c40685e8f8eb">
I set the clams and some of these animals to 0 for them to just keep spawning

**Comment by RayTrace082** [comment]
>Why is there a random rhino in the ocean

It either swam there, or Minecraft decided that a piece of ocean was a tundra

>I set the clams and some of these animals to 0 for them to just keep spawning

Delete the entry, setting it to zero doesn't work when there's no other entry
"entries": [
]

**Comment by lSherozl** [comment]
I am using in control to help me with the over spawning, but please enlighten me since I don't understand the data pack part, I need to delete the word entries? Or are you saying I need to make the JSON start and end with a bracket

**Comment by lSherozl** [comment]
> > Why is there a random rhino in the ocean
> 
> It either swam there, or Minecraft decided that a piece of ocean was a tundra
> 
> > I set the clams and some of these animals to 0 for them to just keep spawning
> 
> Delete the entry, setting it to zero doesn't work when there's no other entry "entries": [ ]

Dont know what you mean by delete the entery, do you have an example you can give, of how a datapack edit should be like?

**Comment by RayTrace082** [comment]
Literally gave you the answer in my comment, here's the answer with the other 3 lines you need to add to the file to be valid

{
  "name":"benthos",
  "entries":[
  ]
}

**Comment by lSherozl** [comment]
> Literally gave you the answer in my comment, here's the answer with the other 3 lines you need to add to the file to be valid
> 
> { "name":"benthos", "entries":[ ] }

Thanks does 0 do anything when there are other entries or no?

**Comment by RayTrace082** [comment]
Never tested it, since deleting the entry does the same thing in a safer way, but an entry weighted as 0 should never get chosen if there's anything else

As said, never tested it, but I'll consider it a bug worth fixing if a 0ed entry still gets chosen
