### ISSUE TITLE
I Repeat Add SnailFish In Minecraft

### ISSUE THREAD

**Issue by CommonTitanLourinensis978968** [RayTrace082/untamedwilds#240]
Add SnailFish A Rare Fish And Also The Deepest Living Fish That Man Has Ever Known They Have A Transparent And Clear Body People Call It SnailFish They Bring Beauty To The Deep Ocean In Minecraft I Want The Next Update There Will Be Snail Fish Because They Are Like Catfish At Time And Half A Snail For Mariana SnailFish Is The Most Beautiful Strange With 2 Species Mariana SnailFish And Festive SnailFish.
![27566_16x9](https://github.com/RayTrace082/untamedwilds/assets/136237517/ca82cd0a-d7de-46ca-8b84-41d31903d859)
![file-20230418-18-25ec26](https://github.com/RayTrace082/untamedwilds/assets/136237517/8b6b04a6-8b11-4619-aec5-cf2dc885ac16)
![mqdefault](https://github.com/RayTrace082/untamedwilds/assets/136237517/152d8417-6d0d-4ff8-95e3-5996238fef4f)
![file-20180911-144458-58n4o4](https://github.com/RayTrace082/untamedwilds/assets/136237517/d9c872ef-831f-4b10-bba5-77e160b72d42)
![1280px-Festive_Snailfish](https://github.com/RayTrace082/untamedwilds/assets/136237517/b2e517f9-9b12-4975-87d1-aad422ccd3e7)

**Comment by RayTrace082** [comment]
Not happening
Now fuck off
