### ISSUE TITLE
Add Special Fish In The Next Update The Barreleyes

### ISSUE THREAD

**Issue by likknnjhoson** [RayTrace082/untamedwilds#241]
![Macropinna_Microstoma](https://github.com/RayTrace082/untamedwilds/assets/136237517/468b6b7e-a2cd-4695-8155-3a3972edff3a) Barreleyes, also known as spook fish (a name also applied to several species of chimaera), are small deep-sea argentiniform fish comprising the family Opisthoproctidae found in tropical-to-temperate waters of the Atlantic, Pacific, and Indian Oceans These fish are named because of their barrel-shaped, tubular eyes, which are generally directed upwards to detect the silhouettes of available prey; however, the fish are capable of directing their eyes forward, as well. The family name Opisthoproctidae is derived from the Greek words opisthe 'behind' and proktos 'anus' The morphology of the Opisthoproctidae varies between three main forms: the stout, deep-bodied barreleyes of the genera Opisthoproctus and Macropinna, the extremely slender and elongated spookfishes of the genera Dolichopteryx and Bathylychnops, and the intermediate fusiform spookfishes of the genera Rhynchohyalus and Winteria.All species have large, telescoping eyes, which dominate and protrude from the head, but are enclosed within a large transparent dome of soft tissue.[5] These eyes generally gaze upwards, but can also be directed forwards.[6] The opisthoproctid eye has a large lens and a retina with an exceptionally high complement of rod cells and a high density of rhodopsin (the "visual purple" pigment); no cone cells are present. To better serve their vision, barreleyes have large, dome-shaped, transparent heads; this presumably allows the eyes to collect even more incident light and likely protects the sensitive eyes from the nematocysts (stinging cells) of the siphonophore…

**Comment by RayTrace082** [comment]
Not taking suggestions
