### ISSUE TITLE
Mobs spawn in the water

### ISSUE THREAD

**Issue by Trixdoesthings** [RayTrace082/untamedwilds#242]
There seems to be a problem with the way you spawn mobs in that they don't seem to have a restriction stopping them from spawning in the water. In my testing they also seem to want to spawn in the water more than they do land.

Big cats, Bison, Boars and Rhinos are big culprits in spawning in the water. They don't spawn in ocean biomes but they do along the coasts that have biome as a land biome. 

You may need to code in a restriction to stop mobs that shouldn't spawn in water from doing so.

**Comment by RayTrace082** [comment]
There's now a config option to do that
