### ISSUE TITLE
Server crash with an entity

### ISSUE THREAD

**Issue by 3ROKS** [RayTrace082/untamedwilds#244]
The server crashes with the entity "Aardvark" I have removed the entity but I can't find any configuration file to disable that entity.
Version: 1.18.2
Mod version: 2.1.3
Log:
[crash-2023-06-16_16.28.51-server.txt](https://github.com/RayTrace082/untamedwilds/files/11773299/crash-2023-06-16_16.28.51-server.txt)

**Comment by RayTrace082** [comment]
Not on the latest version
Try again with that
