### ISSUE TITLE
Creative Tab crashes for client when inside a server

### ISSUE THREAD

**Issue by TqLxQuanZ** [RayTrace082/untamedwilds#245]
Running in single player doesn't not reproduce this issue, it must be done with a server and a client.

Repro Steps:
1. Client joins a server and set to creative.
2. Go to UntamedWilds creative tab.
3. Scrolls down and notice the crash.

Version: untamedwilds-1.18.2-2.4.0.jar

[crash-2023-06-18_15.01.14-client.txt](https://github.com/RayTrace082/untamedwilds/files/11780817/crash-2023-06-18_15.01.14-client.txt)

**Comment by RayTrace082** [comment]
Can't replicate
