### ISSUE TITLE
Highlighter troubles

### ISSUE THREAD

**Issue by ExtraStainedSock** [RayTrace082/untamedwilds#246]
Is there any way to remove the highlighter without killing the entity? (I might be getting my mods mixed up but I remember a highlighter that would only show up when you had it in either hand) 1.16.5
/

**Comment by RayTrace082** [comment]
No way to remove the buff, albeit there's probably some way to do so with commands
The highlighter is an unobtainable debug item and should not be used outside of Creative mode
