### ISSUE TITLE
How to disable a specific plant from spawning. 1.18.2, Ver 2.4.0

### ISSUE THREAD

**Issue by MaroonStingray** [RayTrace082/untamedwilds#248]
I'm working on a personal modpack for myself and I'd like to disable a specific plant from spawning, the Titan Arum. Unfortunately there's no config option to disable it and unlike disabling specific mobs, after much searching I could not find any way of creating a datapack that would disable it. Even the config option to disable flora spawns in a specific biome does not work. If you could offer any advice on creating a datapack, config option, or other way to disable one specific plant without removing any other flora, it would be extremely appreciated as I've been working at this for quite a while now with no success. Thank you for your time.

**Comment by RayTrace082** [comment]
Plants can't be disabled in a case-by-case basis, there's only the master toggle
