### ISSUE TITLE
No mobs spawning period?

### ISSUE THREAD

**Issue by Jaybluebird8709** [RayTrace082/untamedwilds#250]
i have bugger all spawning in the ways of any mobs from this mod or vanilla it seems? idk whats happening, but i do have a few critters from alex's mobs spawning here and there but i cant find a single chicken any where let alone anything that spawns outside of a burrow. bees will spawn but i think thats cause of how beehives work having them already in the hive on worldgen possibly? no bears, foxes, chickens, cows, nothing. fish and such seem to spawn alright from alex's and vanilla... as well as hostile mobs. im a bit miffed if i gots to disable this mod

**Comment by RayTrace082** [comment]
>i have bugger all spawning in the ways of any mobs from this mod or vanilla it seems?

This mod doesn't interact with vanilla spawns in any way. Untamed Wilds mobs spawn outside of normal vanilla spawning, and should not affect other mod's spawns (unless for some reason, enough mobs spawn so as to hit the mob cap)
