### ISSUE TITLE
Camel Oddity?

### ISSUE THREAD

**Issue by BlossomZZ** [RayTrace082/untamedwilds#257]
not really sure how to put this, but a Camel in the 1.19.2 version of the mod goes into the ground if it's sitting on the ground. it'll do the standing-up animation, but its legs will go upward while the body and head go downwards into the ground. kinda hard to explain, so hopefully these screenshots will explain it better
![2023-08-11_03 48 12](https://github.com/RayTrace082/untamedwilds/assets/141999786/018bd2a8-7d84-42e5-88a8-3832e1ce146b)
![2023-08-11_03 48 04](https://github.com/RayTrace082/untamedwilds/assets/141999786/302e3d0e-ae6a-4fc2-8632-1cef43362a40)

**Comment by RayTrace082** [comment]
Fixed in the latest 1.20 version

This issue is purely visual, the camel (or mob) is fully functional, and will go back to normal when prompted. The Sleeping and Sitting positions are being both applied at once
