### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Joel1234545** [RayTrace082/untamedwilds#258]
Where can I find Great White Sharks, I been having trouble finding any at all? I also use biome of plenty if that helps.

**Comment by RayTrace082** [comment]
Deep Ocean / Deep Cold Ocean, ~20% of all Sharks should be Great Whites. Most mobs use biome tags, but Ocean ones need vanilla biomes to spawn

Reference:
https://github.com/RayTrace082/untamedwilds/blob/1.18.2/src/main/resources/data/untamedwilds/entities/shark.json

**Comment by Joel1234545** [comment]
Thx found it and I can't find any burrows for monitor lizards burrows, I found the other ones such as snakes, etc but no monitor lizard burrow, I want to know the chance like 10% or what is the chance that a burrow spawns with monitor lizards.

**Comment by RayTrace082** [comment]
Monitor lizards do not spawn in burrows, they spawn in the world

**Comment by Joel1234545** [comment]
Oh okay, but I can't find any at all I check big chunks of land like the swamp where some species are suppose to spawn and no?

**Comment by Joel1234545** [comment]
and can you please port the new mobs from 1.20.1 to 1.19.2?

**Comment by Joel1234545** [comment]
and I am also using biome of plenty if that affects the spawn rates?

**Comment by Joel1234545** [comment]
and can u make it so 
-Re-enabled behavior where (wild) Big Cats will flee combat when under 40% HP

in 1.19.2 so sorry if I am asking for too much I just play a lot on 1.19.2 and if ur not going to update 1.19.2 can u please notify me so I know

**Comment by RayTrace082** [comment]
Not going to port code changes.

Depending on how much of a hassle it is, I will port the mobs and any (simple) bugfixes back to 1.18 and 1.19, even if your behavior makes me want to ditch 1.19 for good

**Comment by Joel1234545** [comment]
Sorry to hear that my behavior online is not that good as of a moment, I will try to improve it and have more patience. I know it's hard for you since you are the only person working on this mod. (I believe)

**Comment by RayTrace082** [comment]
There have been a few people contributing to the code and submitting translations, but yes, I am the main developer

Requesting backports/updates is frowned upon for good reason, every update there's usually large internal changes that make the process of porting content tedious, and being nagged about it doesn't help when the reason modders make mods is enjoyment
