### ISSUE TITLE
Unable to Tame animals in 1.20.1

### ISSUE THREAD

**Issue by Fluffy-Beolf** [RayTrace082/untamedwilds#260]
I've tried multiple methods looking at online guides and such and it doesn't work, all the things it says to try are outdated, I'm sure this is probably just like a thing of "it's just been updated to this version" but I wanted to report it anyway incase its not.

**Comment by RayTrace082** [comment]
Taming hasn't changed, it's just a bug with the AI

Will upload a fix soon

**Comment by Fluffy-Beolf** [comment]
> Taming hasn't changed, it's just a bug with the AI
> 
> Will upload a fix soon

Ah, thank you for the update
