### ISSUE TITLE
[1.18.2] Excessive console spam during world generation

### ISSUE THREAD

**Issue by lilchicky** [RayTrace082/untamedwilds#266]
While the server is preparing chunks, this mod is spamming numbers between 0 - 99 like crazy.

MC 1.18.2
Forge 40.2.10
Untamed Wilds 2.4.1

![image](https://github.com/RayTrace082/untamedwilds/assets/120543766/f5370826-feb3-4668-b916-cdc3b3141b8d)

**Comment by lilchicky** [comment]
looks to me like a debug line that wasn't removed haha

**Comment by RayTrace082** [comment]
Every time 🤦‍♂️

**Comment by thebugeater22** [comment]
Same issue, same version, was not present in the prior version so I was confused when this started lmao

![IMG_4362](https://github.com/RayTrace082/untamedwilds/assets/143335112/77ce62a8-43ba-40e9-a20c-7eafd8a7869a)
