### ISSUE TITLE
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: untamedwilds:egg_tarantula_black_and_whıte

### ISSUE THREAD

**Issue by Onat125** [RayTrace082/untamedwilds#27]
[crash-2021-07-05_23.34.47-fml.txt](https://github.com/RayTrace082/untamedwilds/files/6766156/crash-2021-07-05_23.34.47-fml.txt)

**Comment by RayTrace082** [comment]
Duplicate of #24
