### ISSUE TITLE
No Gaint Pandas, Monitor Lizards or Opussum 1.19.2 latest verison

### ISSUE THREAD

**Issue by Joel1234545** [RayTrace082/untamedwilds#271]
I make countless worlds and and search the correct biomes but still could not find the animals listed on top.  I have a lot of mobs in my worlds so idk if that affects it but the only main animal mod I have is untamed wild I did not have Alex mobs, I also use biome of plenty.

**Comment by Joel1234545** [comment]
I have ecologist too

**Comment by Joel1234545** [comment]
And also is 1.20.1 maybe I have a certain setting on or something for the mobs not to spawn

**Comment by Joel1234545** [comment]
@RayTrace082 

I have a image too it says 0 monitors loaded

**Comment by Joel1234545** [comment]
And no there are not rare there is just simply no monitor lizard in my world or opossum, its a bug idk why dont they don't spawn I been having this issue for the longest 1.20.1 maybe I have certain setting or something I use forge and the Minecraft Laucher.

**Comment by RayTrace082** [comment]
Yeah, I found (and fixed) the source of the issue, the code got Mojang'd and Monitors and Opossums do not currently spawn

**Comment by Joel1234545** [comment]
Okay
So I should be able to find monitor and opossums now

**Comment by Joel1234545** [comment]
Or do I have to download something or fix a setting or something rn im looking and still nothing if not how do I fix it then

**Comment by RayTrace082** [comment]
The changes do not apply until I upload the fixed version to Curseforge
