### ISSUE TITLE
No mobs loading into the world

### ISSUE THREAD

**Issue by Jollyolsport** [RayTrace082/untamedwilds#273]
Forge Version:  40.2.10
Minecraft Version: 1.18.2
Untamed Wilds Version: 1.18.2-2.4.2

No mobs spawn when I create a new world or load new chunks. Flora like the temperate bush generates though. 
I can still spawn in mobs via their eggs.
Im running a few other mods and can list upon request, however some of the world generation mods include:
Dynamic trees, Dynamic Trees+, Dynamic Trees Tectonic, Tectonic

**Comment by RayTrace082** [comment]
Fixed in the 2.4.3 version I just uploaded
