### ISSUE TITLE
Mobs spawn in the sea

### ISSUE THREAD

**Issue by AMRH2000** [RayTrace082/untamedwilds#274]
Mobs spawn in the sea
1.20.1
untamedwilds-1.20.1-4.0.4
forge 47.1.3
citadel-2.4.4-1.20.1

**Comment by WimpieRatte** [comment]
Also finding land mobs (rhino's, bears, boars, etc.) on the water in rivers too.
Definitely unnatural, how frequent this is.

**Comment by KPaXz** [comment]
Ive also noticed a mass amout of untammed wild mobs in the water and odd water swimming behaviour.
the manatee does a tight spin at times going up and down in the water. the cat was running in place in the water. sleeping boars in water.

MOD LIST:
[dynamiclightsreforged, aether_enhanced_extinguishing, supermartijn642configlib, betterwitchhuts, geckolib, deepslatecutting_forge, aether, illagerinvasion, betteroceanmonuments, sophisticatedcore, rubidium, sodium, nyfsquiver, gpumemleakfix, insanelib, xaeroworldmap, modernfix, citadel, alexsmobs, netherite_horse_armor, yungsapi, mixinextras, bookshelf, sophisticatedbackpacks, twigs, sweetberryfoods, lost_aether_content, swampier_swamps, shieldexp, betterfortresses, cloth_config, dragonmounts, leavesbegone, twilightforest, growthcraft, growthcraft_apiary, growthcraft_apples, growthcraft_bamboo, growthcraft_cellar, growthcraft_milk, growthcraft_rice, structure_gel, industrialforegoing, farmersdelight, amplifiednether, tempad, ambientsounds, jearchaeology, getittogetherdrops, endersdelight, endrem, supermartijn642corelib, resourcefulconfig, pamhc2foodextended, better_berries, curios, patchouli, cobble_tostoneviceversa_mr, collective, spyglass_improvements, horse_colors, elevatorid, bedrockplus, betterstrongholds, buildersaddition, resourcefullib, cumulus_menus, fennecfox, twilightdelight, inventoryprofilesnext, deeperdarker, architectury, doapi, terraform, vinery, dynamictrim, justhammers, allthetrims, cupboard, betterendisland, enhancedai, nitrogen_internals, rubidium_extra, l2library, deep_aether, chickensshed, letmedespawn, disenchanting, bettermineshafts, yeetusexperimentus, shulkerboxtooltip, scaffoldingdropsnearby, betterjungletemples, betteradvancements, fallingtrees, waterdripsound, insects_recrafted, puffish_skills, puzzlesapi, tameablebeasts, pamhc2trees, mutantmonsters, rechiseled, easymagic, jei, visualworkbench, callablehorses, mekanism, mekanismgenerators, mekanismtools, stoneworks, enlightened_end, easyelytratakeoff, clumps, comforts, naturescompass, untamedwilds, aethersteel, better_berries_plus, bagofholding, everycomp, betterdeserttemples, catalogue, terralith, packingtape, fusion, mythicmounts, puzzlesaccessapi, forge, travelerstitles, toofast, ironchest, nyfsspiders, minecraft, voicechat, trade_cycling, libipn, terrablender, biomesoplenty, moonlight, titanium, immersiveengineering, mixinsquared, jade, pamhc2crops, firstpersonmod, creativecore, spectrelib, domum_ornamentum, aeroblender, kotlinforforge, flywheel, create, brutalbosses, xaerominimap, pamhc2foodcore, gravestone, croptopia, experienceobelisk, polymorph, storagedrawers, canary, brutes_dropscraps_mr, fps, bettertridents, appleskin, ferritecore, biomemusic, puzzleslib, aquaculture, friendlyfire, wwoo, musicmanager, createaddition, cristellib]

![2023-10-07_15 34 12](https://github.com/RayTrace082/untamedwilds/assets/111913726/6feab4fb-9bb9-4b1a-9fd0-7baa30d84ff4)
![2023-10-07_15 34 31](https://github.com/RayTrace082/untamedwilds/assets/111913726/42e7bad5-535c-4c5f-8f8a-d88d30453589)
![2023-10-07_15 35 25](https://github.com/RayTrace082/untamedwilds/assets/111913726/91c67c39-ead0-46cd-b811-8e494b1a8de4)
![2023-10-07_15 35 38](https://github.com/RayTrace082/untamedwilds/assets/111913726/05724051-fae5-465e-a58b-a4242f2969aa)
![2023-10-07_15 28 55](https://github.com/RayTrace082/untamedwilds/assets/111913726/9a1e3ba8-da25-4391-bc00-3f183c75185e)
![2023-10-07_15 30 31](https://github.com/RayTrace082/untamedwilds/assets/111913726/358d3b9e-6bac-49f5-82b4-37f693975d61)

**Comment by RayTrace082** [comment]
About mobs spawning in water, there is a config option "blockSpawnsInWater" that was added in the latest 1.20 version. Not going to change the default behavior, however

About shitty pathfinding in Water, 1.20 broke something about swimming, so mobs can't trigger their AI properly, which I am on the process of fixing

**Comment by AMRH2000** [comment]
Mob spawning with blockSpawnsInWater is fixed for now but the bears spawn in the cave, do you have a solution for that?
