### ISSUE TITLE
No Mobs

### ISSUE THREAD

**Issue by effectedelk** [RayTrace082/untamedwilds#278]
1.18.2-2.4.2

No mobs except for lizards and ocean aquatics will spawn. Plants also spawn in just fine. I've loaded new worlds/traveled to new chunks/etc but I can't get anything other than those first listed to spawn naturally. I have the same issues with 1.18.2-2.4.1 but not 1.18.2-2.4.0.

**Comment by RayTrace082** [comment]
Fixed in the 2.4.3 version I just uploaded
