### ISSUE TITLE
About Citadel

### ISSUE THREAD

**Issue by KaxelDreamhack123** [RayTrace082/untamedwilds#296]
Hello, sorry pls for this question but i really want to understand how to make animations for Citadel mod. I know about Blockbench but i dont know how create animation to code like methods animate from Models(Entity). I asked many people but they just silence.

**Comment by RayTrace082** [comment]
I don't think its possible to export Blockbench animations to be used by Citadel, at least, I don't do that. 
There's two kinds of animations. Keyframe animations are the ones that need to be triggered by code (eg. Bears randomly standing up, or attack animations) and non-keyframe animations are those that happen automatically based on context (eg. walking or swimming)

For keyframe-based animations:
I use 1.12 Tabula to make models, which has an animator (but no way to export them), once I am happy with the animation, I just type the same numbers from Tabula into my Model class

For non-keyframe-based animations:
Citadel is optional, but it makes it a lot easier, I just type numbers that may look decent, and then using the reload tool from IDEA fine-tune the numbers into something that looks good
