### ISSUE TITLE
Pick up mob config / item

### ISSUE THREAD

**Issue by Maxion78** [RayTrace082/untamedwilds#3]
**Describe the suggestion**
It is too easy to kill a snake as you can just right-click on.

**Expected behavior**
Make a config option : pick up snake. Or make an item that allows you to pick up spiders, snakes, ...

**Additional context**
This mod is so underrated, I looove It ;)

**Comment by RayTrace082** [comment]
To be fair, Snakes are not meant to be any kind of serious threat, I have considered having to use a Stick to pick up Snakes, but it doesn't really add much to the game

That said, I have added a Config option to prevent angered mobs from being catchable, disabled by default (applies to picking up mobs and Cage traps)
