### ISSUE TITLE
Game crashes whenever animal is about to be born

### ISSUE THREAD

**Issue by MoonyX-3** [RayTrace082/untamedwilds#30]

**Comment by MoonyX-3** [comment]
It crashes every single time, and if eventually you manage to save the game and not get stuck in an infinite time loop caused by crashes the baby animals simply doesn't exist. It also seems to happen with all forge versions, not sure if that helps. Great mod overall though.

**Comment by RayTrace082** [comment]
Fixed in the latest hotfix
