### ISSUE TITLE
Mod crashes when my Blind Cave Bear gave birth!

### ISSUE THREAD

**Issue by KATARR69** [RayTrace082/untamedwilds#31]
so, first of all when i started it im using the easy breeding gamerule, however it just crashed the game instantly, but then i tried turning it off and wait for the pregnancy time but it still crashes when the pregnancy time is over.
EDIT:Jaguars crashed too, however hyenas and rhinos don't.

**Comment by RayTrace082** [comment]
Fixed in the latest hotfix
