### ISSUE TITLE
Interaction With McJtyLib, Optifine, RFToolsBase, And Several Other Mods Crashes Game

### ISSUE THREAD

**Issue by runningwithscissors1337** [RayTrace082/untamedwilds#36]
I have no idea what kind of absurd edge case this specific arrangement causes, but so far I have tested 7 of the mods in my list, and if even one of them is missing the error that crashes the game never occurs (though since many are dependencies for eachother there are still errors). So far I have tested the following:

McJtyLib 1.16-5.0.21
Optifine 1.16.5_HD_U_G8
RFToolsBase 1.16-2.0.11
Cuneiform 1.16.3-1.2.5
Yung'sAPI 1.16.4-Forge-11
ImmersivePortals 0.16-mc1.16.5-forge
Untamed Wilds 1.16.5-1.3.0

There absolutely could be more, and if you'd like I can try to find more, but for now here is the crash log, which should contain the full modlist.
[Crash1.txt](https://github.com/RayTrace082/untamedwilds/files/6865304/Crash1.txt)

**Comment by runningwithscissors1337** [comment]
Correction: You can close this issue if you want, while for the first few launches removing Untamed Wilds worked, it no longer does,  I have no clue why. Sorry about this.

**Comment by RayTrace082** [comment]
Yes, UntamedWilds does not touch Mixins, and that's what is causing your game to fail. I'm quite sure Optifine is the culprit, but with Mixin issues, it's hard to know

While I don't know much about Optifine, try downgrading your Forge version (36.1.10) to 36.1.0, as that's the version that Optifine G8 was built against
