### ISSUE TITLE
Suggestion: Accurate version of vanilla tropicalfishes

### ISSUE THREAD

**Issue by Beam196** [RayTrace082/untamedwilds#37]
list of tropicalfishes:
1.clownfishes: (commons, pinks, tomatoes, saddlebacks, yellowtails)​ they are passive mobs that living in non cold and non frozen oceans can be seen swimming near anemonies in school in 2-4 fishes they drop tropicalfish and bonemeals and rarely clownfish roes and bucketable with water bucket 2.surgeonfishes: (blue tangs, yellow tangs, black tangs, purple tangs, sailfin tangs)​ they are passive mobs that living in non cold and non frozen oceans can be seen swimming in school in 2 fishes if you touch them there are 25% chance to sting you with 1 damage they drop tropicalfish and bonemeals and rarely surgeonfish roes and bucketable with water bucket
3.parrotfishes: (blues, yellowfins, commons, globeheads, bridleds) they are passive mobs that living in non cold and non ​frozen oceans can be seen swimming in school in 1-2 fishes eating corals then more corals will growing up they drop tropicalfish and bonemeals and​ rarely parrotfish roes and bucketable with water bucket
4.butterflyfishes: (raccoons, copperbands, yellow longnoses, maskeds, saddleds, moorish idols (actually they aren't butterflyfishes but they are similar to bannerfishes), bannerfishes)​ they are passive mobs that living in non cold​ and non​ frozen oceans can be seen swimming in school in 2-4 fishes except yellow longnose butterfly that always swimming in school in 2 fishes one is male and one is female they are territorial to their own species in other school and attack them with 1 damage until their reach 50% health they drop tropicalfish and bone​meals and rarely butterflyfish roes and bucketable with water bucket
cleaner wrasses: (bicolors, bluestreaks, hawaiians, blackspots, redlips)​ they are passive mobs that​ living in non cold and non frozen​ oceans can be seen swim in school in 2-6 fishes eating parasites in bigger animals and players then they will get regeneration 2 for 5 seconds if their health dropped before they drop tropicalfish and bonemeals and rarely cleaner wrasse roes and bucketable with​ water bucket
5.marine angelfishes: (bluerings, emperores, blue-gridleds, sixbars, yellowfaces, frenches, semicircles)​ they are passive mobs that living​ in non cold and non frozen oceans can be seen swim in school in 4-6 fishes they drop tropicalfish and bone​meals​ and rarely marine angelfish roes and bucketable with water bucket
6.basslets: (brazilians, blackcaps, goldens, royals, yellowlineds)​ they are passive mobs that living in non cold and non frozen oceans can be seen swim in school in 4-6 fishes they drop tropicalfish and​ bone​meals ​and ​rarely basslet roes and bucketable with water​ bucket
7.pufferfishes: (blue-spotteds, maskeds, white-spotteds, yellow-eyeds, narrow-lined)​ they are passive mobs that living​ in non cold and non frozen oceans can be seen swim in school in 1-2 fishes if you appraoch them they will puff up and sting you with poison 1 for 30 seconds they drop pufferfish and bonemeals and rarely pufferfish roes and bucketable with water bucket
8.seahorses: (commons, pygmies, spinies, big-bellies, long-snouteds)​ they are passive mobs that living in non cold and non frozen oceans can be seen swim in school in 2-6 seahorses and perch in seagrasses, kelps and corals they drop raw seahorse which can be cook to eat and bone meals and rarely seahorse roes and bucketable with water ​bucket

**Comment by RayTrace082** [comment]
Sorry, but I am not taking suggestions when it comes to new mobs
That said, I do have models in the oven for at least 2 of those :)
