### ISSUE TITLE
Missing texture(purple-black) on some mob variants

### ISSUE THREAD

**Issue by Atopik2** [RayTrace082/untamedwilds#41]
the title says it all and i have optifine 1.16.5 g7

**Comment by RayTrace082** [comment]
I can't do anything without any further information
Does it affect all mobs, or just specific ones? Is it a particular species? Are you using any resource pack? Does it work if you remove Optifine? because it's notorious in modded Minecraft for breaking other mods

**Comment by Atopik2** [comment]
it affesct specific mobs like all tarantulas are normal but the tiger and king variations are missing textures is there a way for me to disable only king and tiger tarantulas?
