### ISSUE TITLE
Snakes Keeps Getting Despawned Even When Named

### ISSUE THREAD

**Issue by BobbyLinMC** [RayTrace082/untamedwilds#48]
Hello. I have an issue with the snakes. I made a terrarium in one of my homes and I had a snake in the terrarium. After the first time the snake despawned. I summoned and placed the new snake in the terrarium and this time I named him. I went away from the terrarium for a while, but when I came back to the terrarium, the snake despawned again. I think he died, because the snake left a snake skin. Idk what's causing this issue. Maybe it has to do with the plants I use for decorating the terrarium? I have 2 Glowberries vines and one stem of Dripleaf. Is the lack of space causing this issue? The terrarium is 3 by 1 blocks and it is built in the wall. Do I need a burrow for the snake from despawning? This doesn't happen to the soft shell turtles, only the snakes. Plzz HeLp!!!1!!!!

**Comment by RayTrace082** [comment]
Mobs do not despawn under any circumstance (exception being mobs belonging to a burrow, kinda). There's also a notorious, rare bug in vanilla where a mob close to a wall may suffocate in solid walls: [MC-2025](https://bugs.mojang.com/browse/MC-2025)

That said, the most likely explanation is that some hostile mob spawned/made its way inside the terrarium and angered the snake, which attacked it and got killed
