### ISSUE TITLE
Burrow Critters not following despawn request when max range of player is exceeded

### ISSUE THREAD

**Issue by VallenFrostweaver** [RayTrace082/untamedwilds#49]
Minecraft 1.16.5
Forge 36.2.2
Untamed Wilds 1.16.5-1.3.1

I changed the config settings of burrows from the default 40 to 2 and it worked so that burrow critters popped back in the burrow (despawned) if the player backed away. The issue is that on the second time a critter spawned from the burrow they then ignored that rule and continued to wander away regardless of player distance. This means it works... but only on the first try.

**Comment by RayTrace082** [comment]
Duh, I was erasing that data when converting mobs into NBT to prevent issues when moving mobs, but forgot that it was really necessary to keep it for mobs that naturally despawn into their burrow

It is now fixed in-dev
