### ISSUE TITLE
quick and massive reproduction of sharks

### ISSUE THREAD

**Issue by antmansel** [RayTrace082/untamedwilds#50]
when in the aquarium I gave myself only one shark, after a few days suddenly there were dozens of them and you probably know what my problem is
![2021-08-23_22 22 59](https://user-images.githubusercontent.com/89421688/130516992-75b8fe04-eb54-446c-a842-ece99a2c3afb.png)

**Comment by RayTrace082** [comment]
Fixed in-dev, turns out Sharks were missing some checks and could breed with themselves if they are female
