### ISSUE TITLE
big mobs attacks player even though theres a solid wall blocking them

### ISSUE THREAD

**Issue by KATARR69** [RayTrace082/untamedwilds#52]
- i put my big cat(untamed) into a 2x2 inclosure made out of glass but when i want to see them i still get hurt even though there is no way i can hit them, also happens with bears, and sharks when im on the beach and it attacks me in a ridicolous range
maybe u should nerf the reach on them?

**Comment by RayTrace082** [comment]
Should be fixed by the next version
