### ISSUE TITLE
game crashes while on loading screen when optifine isnt used and i cant join my aternos server with the same version of the mod when i use optifine for some reason

### ISSUE THREAD

**Issue by Hakkibey1** [RayTrace082/untamedwilds#57]
[crash-2021-09-12_19.45.38-fml.txt](https://github.com/RayTrace082/untamedwilds/files/7149957/crash-2021-09-12_19.45.38-fml.txt)
above is the one without optifine

**Comment by RayTrace082** [comment]
Duplicate of #24
