### ISSUE TITLE
1.16.5 crash forge 36.2.0

### ISSUE THREAD

**Issue by Mr-Syntax** [RayTrace082/untamedwilds#68]
Just had this ticking entity crash upon entering the map

ive just added I like wood + byg comp expansion (these are not in the current release might release later tonight)

havent really had it before 

here is the log
[crash-2021-10-05_05.02.31-server.txt](https://github.com/RayTrace082/untamedwilds/files/7282459/crash-2021-10-05_05.02.31-server.txt)

**Comment by Mr-Syntax** [comment]
and this is the pack it happend in
https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by RayTrace082** [comment]
Sorry, but the stacktrace doesn't point out anywhere in my mod. There's this line:

`Entity's Vehicle: ~~ERROR~~ NullPointerException: null`

That *may* be causing it, but I do not touch vehicles/mounts anywhere in the mod, so there's nothing that could be bugged to begin with. Can this crash be reliably replicated with these mods?

When minecraft crashes, a latest.log file should be generated in /.minecraft/logs, could you attach this file so I can take a deeper look into it?

**Comment by RayTrace082** [comment]
Closing due to lack of information
