### ISSUE TITLE
Lions spawn torches when hitting the player (possibly incompatible with colds steel)

### ISSUE THREAD

**Issue by Mr-Syntax** [RayTrace082/untamedwilds#69]
as the title says, when i was attcked by a lion it would spawn torches at the place i was hit on the ground like when you have the torch bringer enchant from colds steel

it was in this pack

https://www.curseforge.com/minecraft/modpacks/chosencraft

possibly incompatible with this mod

https://www.curseforge.com/minecraft/mc-mods/colds-steel

**Comment by RayTrace082** [comment]
Shit

There is no incompatibility here, I do spawn Torches as a quick and dirty check to debug which exact blocks the Lion AI is targeting, but forgot to disable that functionality for the final release. Fortunately, this should only happen when a Lion tries to jump over a gap, and not any other mob

Already solved it, but it's not going to make it into a new release anytime soon

**Comment by Mr-Syntax** [comment]
ahh well okay you shit happens :D as long as it isent crashing anything im good :)
