### ISSUE TITLE
Temperate bush breaking animation

### ISSUE THREAD

**Issue by devjavu7** [RayTrace082/untamedwilds#71]
The breaking animation when breaking a temperate bush in survival is "weird" and hard to describe.

Break a temperate bush in survival.

![2021-11-14_07 43 15](https://user-images.githubusercontent.com/88561769/141670665-5c9130d1-fb40-4811-8b61-6afdd4bffdbf.png)

 - Minecraft version: 1.16.5
 - Version of the mod: 1.4.1
 - Additional mods: I'm only gonna list the mods, if the problem is not reproducable.

**Comment by RayTrace082** [comment]
While this is a vanilla issue about which I can't do anything about, I can make it less egregious through model magic

Should be fixed by next version
