### ISSUE TITLE
Trevally Spawns

### ISSUE THREAD

**Issue by TheSleepySpino** [RayTrace082/untamedwilds#73]
**Describe the solution you'd like**
A clear and concise description of what you would like to happen.

I personally would like trevally spawns to be reduced. I, along with many others, have many other animal mods that add plenty of new oceanic animals. The current trevally spawns are rather high, in fact I can't look one direction in a warm ocean without seeing at least one of them. This makes finding the other really cool sea creatures from other mods rather difficult and tiresome. I couldn't find an UAM eel until after boosting their spawn rates and looking around for 3 hours, and this isn't an uncommon occurrence when looking for other aquatic animals.

**Describe alternatives you've considered**

I _could_ use a spawn-editing mod but I nor many others know how

**Additional context**
Add any other context or screenshots about the feature request here
![2021-11-21_18 28 25](https://user-images.githubusercontent.com/80644978/142783195-c8028fed-1882-45c7-b95d-56e4e468ed8e.png)
.

**Comment by RayTrace082** [comment]
Huh, while there is indeed an issue with Trevally spawns (mostly, there's not a lot of mob variety in oceans, and Trevallies happen to be the default), it shouldn't matter in this case. Untamed Wilds mobs do not take up any vanilla spawn. That's one of my gripes about mob mods, and why I designed my mod in this way

Here's two possible problems:

* Vanilla mob spawning RNG is screwed. This is hard to notice in vanilla, but it gets really obvious as you add entity mods. Basically, you will see only the same type of mobs over wide areas

* There may indeed be enough Trevallies/mobs to actually hit the spawn cap, albeit this shouldn't happen with the default values
