### ISSUE TITLE
Burrows on ice covered rivers

### ISSUE THREAD

**Issue by Maltshakes** [RayTrace082/untamedwilds#76]
Found a burrow that spawned on the ice of a frozen river biome. Unsure if this is intended or not

**Screenshots**
https://i.imgur.com/pqszIfS.jpg

**Version (please complete the following information):**
 - Minecraft version: 1.16.5
 - Version of the mod: 1.5.0

**Comment by RayTrace082** [comment]
Mostly intended, as Ice is a valid block when it comes to spawning, the burrow will just break if the Ice under it melts
That said, I'll remove Salamanders from frozen rivers, since it's pretty dumb
