### ISSUE TITLE
Volume of added animal sounds not based on player position

### ISSUE THREAD

**Issue by Maltshakes** [RayTrace082/untamedwilds#78]
**Describe the bug**
The sounds added for animals (for example: big cats, hippos, and bison) do not lower in volume when the player is far away or is walking away from the source of the sound. I tried putting together a short video to show how it compares to vanilla sheep sounds as you get further away. 

https://youtu.be/InXmSdvxx3s

**Version (please complete the following information):**
 - Minecraft version: 1.16.5
 - Version of the mod: 1.5.0

**Comment by RayTrace082** [comment]
Well, this was incredibly stupid

Turns out it's a bug from vanilla [(MC-146721)](https://bugs.mojang.com/browse/MC-146721), and it turns out I just have to change the .ogg files to be Mono instead of Stereo. Will be fixed by next release
