### ISSUE TITLE
Mod Conflict with ImmersiveFX and Dynamic Surroundings and also wrong .ogg implementation

### ISSUE THREAD

**Issue by Y3Z0N** [RayTrace082/untamedwilds#81]
The sounds of your Entities are Stereo Files instead of Mono Files.
Please Convert all Entity Sound Files into **MONO File**s.

Using Stereo Files for Mob Sounds is wrong. you should convert them.

**Comment by Y3Z0N** [comment]
i commited please apply my commit so its fixed asap :)

**Comment by RayTrace082** [comment]
Was fixed as part of #78

The version including this fix just got released
