### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by teeheeee** [RayTrace082/untamedwilds#84]
java.lang.StackOverflowError
I keep getting this message every time I log on to my server.

I have updated it to the new file uploaded today on the first but I keep crashing getting that message.
I was told by my server host support that the fishes are the reason I am crashing, and when I removed the mod the game went smoothly.

**Version (please complete the following information):**
 - Minecraft version: 1.16.5
 - Version of the mod: 1.5.2
 - Additional mods: These are the mods I use it with
Bookshelf (by DarkhaxDev)
Just Enough Items (JEI) (by mezz)
Goblin Traders (by MrCrayfish)
Nether's Delight (by lumpazl)
CosmicNPCs (by Namensammler42)
Visual Workbench [Forge] (by Fuzs_)
Falling Leaves (Forge) (by Cheaterpaul)
Inventory Pets (by Purplicious_Cow_)
Bamboo Blocks (by TeamAbnormals)
Darker Depths (by naterbobber)
Savage & Ravage (by TeamAbnormals)
Neapolitan (by TeamAbnormals)
Upgrade Aquatic (by TeamAbnormals)
Storage Drawers (by Texelsaur)
End Remastered (by jack_bagel)
AppleSkin (by squeek502)
Valhelsia Core (by ValhelsiaTeam)
GraveStone Mod (by henkelmax)
Fins and Tails (by Coda1552)
Enchant With Mob (by bagu_chan500)
Buzzier Bees (by TeamAbnormals)
Infernal Expansion (by InfernalStudios)
Atmospheric (by TeamAbnormals)
Architect's Palette (by Jsburg)
Enhanced Mushrooms (Forge) (by team_aurora_modding)
BetterEnd (Forge) (by Beethoven92)
Fox's Handheld Cannon (by foxinthebox__)
Environmental (by TeamAbnormals)
Runelic (by DarkhaxDev)
Dungeons Mobs (by the_infamous_1)
Citadel (by alex_khaan)
GeckoLib (by ThanosGecko)
Dark Utilities (by DarkhaxDev)
Immersive Engineering (by BluSunrize)
Guard Villagers (by almightytallestred)
Biomes O' Plenty (by Forstride)
The Endergetic Expansion (by TeamAbnormals)
FramedBlocks (by XFactHD)
[Fabric/Forge] Market Crates 1.16/1.17/1.18 (by lfaoanl)
Crafting Tweaks (by BlayTheNinth)
Immersive Petroleum (by Flaxbeard)
Create (by simibubi)
Dynamic Surroundings (by OreCruncher)
Psi (by Vazkii)
mutil (by mickelus)
Valhelsia Structures (by ValhelsiaTeam)
Patchouli (by Vazkii)
More Minecarts and Rails (by goldey3)
PneumaticCraft: Repressurized (by desht_08)
JourneyMap (by techbrew)
Structure Gel API (by ModdingLegacy)
Mekanism (by bradyaidanc)
Dungeons Gear (by the_infamous_1)
Sophisticated Backpacks (by P3pp3rF1y)
Botania (by Vazkii)
CaveBiomeAPI [Forge] (by blackgear27)
Supplementaries (by MehVahdJukaar)
Quark (by Vazkii)
Turtlemancy (by alienpatois)
Bag of Yurting (by Commoble)
Farmer's Delight (by vectorwing)
Aquaculture 2 (by Shadowclaimer)
Puzzles Lib [Forge] (by Fuzs_)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Decorative Blocks (by stohun)
The Twilight Forest (by Benimatic)
AutoRegLib (by Vazkii)
Blueprint (by TeamAbnormals)
Cyclic (by Lothrazar)
Autumnity (by TeamAbnormals)
Curios API (Forge) (by TheIllusiveC4)
Dungeons Plus (by ModdingLegacy)
Tetra (by mickelus)
ForgeEndertech (by EnderLanky)
Alex's Mobs (by alex_khaan)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Flywheel (by jozufozu)
Advanced Hook Launchers (by EnderLanky)
Spiders 2.0 (by TheCyberBrick)
Dungeons Libraries (by Patrigan)
Selene Lib (by MehVahdJukaar)

**Comment by RayTrace082** [comment]
Consider posting some kind of log if you expect me to fix the problem
