### ISSUE TITLE
Aardvark Crash?

### ISSUE THREAD

**Issue by jiminn-lee** [RayTrace082/untamedwilds#85]
**Describe the bug**
Happened after death, went to death location to pick up stuff (Used the [Gravestone Mod](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod)), when I went to the location the screen froze and crashed before breaking the gravestone. After restarting Minecraft I could break the gravestone and move around for a few seconds before it froze again leading to another crash. Now, when loading up the world it freezes immediately.

**Steps To Reproduce**
Unable to reproduce

**Crash Log**
https://pastebin.com/crpnwG5y

**Version (please complete the following information):**
 - Minecraft version: 1.16.5
 - Version of the mod: 1.5.1, 1.5.2, 1.4.1
 - Additional mods: (Mod list in crash log pastebin)

**Comment by RayTrace082** [comment]
Can't replicate this at all, but I have changed the skins to return an empty resource location instead of crashing
There will probably be a burrow with Aardvarks with a missing texture, however, but nothing major
