### ISSUE TITLE
Server crashes at certain point.

### ISSUE THREAD

**Issue by flareofghast** [RayTrace082/untamedwilds#90]
**Describe the bug**
Server crashes

**Steps To Reproduce**
It now crashes when my son enters the game.

**Crash Log**
[crashed](https://pastebin.com/TxG9ccxb)

**Version (please complete the following information):**
 - Minecraft version: 1.16.5
 - Version of the mod: 1.5.2
 - Additional mods: please see the crashlog

**Comment by flareofghast** [comment]
Just a note, I tried updating Java to v15 (was 11), no change in behaviour. 
Also tried disabling all mobs in config with no change and changing the master switch in config with no change.

**Comment by RayTrace082** [comment]
Disabling stuff does not retroactively remove them from the world, and seeing the log, I can't pinpoint what is the reason why this mob spawned with a bad variant (99, the value I use to mark an entity for removal), but I have added a couple fallbacks when an entity with variant 99 tries to load, which **may** fix this problem after rebooting

**Comment by flareofghast** [comment]
#83 may be related
Trying to boot up my previous server with the new version [crashed on load](https://pastebin.com/FCw26Sjb).

**Comment by flareofghast** [comment]
Restarted it with 1.5.2 and it did the same thing. Copied back 1.5.3 and this time it started up.... go figure.

**Comment by juan-db** [comment]
It looks like I am having the same issue.

Leaving the crash report here in case it might provide some additional insights.
https://pastebin.com/jCXkeDn6

**Comment by RayTrace082** [comment]
Forgot to mention, but the "fix" was only added in 1.5.3 (not really a fix, since I still don't know what caused it, but if the issue happens again, on reboot it should lock entity variants to a valid value)

@juan-db You are using an outdated version, update the mod

**Comment by flareofghast** [comment]
crash on starting the server, but then runs next time I start the server.
[crashed](https://pastebin.com/0naMtggw)

**Comment by juan-db** [comment]
@RayTrace082 I did try with the most up-to-date version of the mod after posting the crash report last time, but I got a very similar, if not the exact same, exception: https://pastebin.com/83L2a7ta

**Comment by flareofghast** [comment]
heres another  [crash on connection](https://pastebin.com/NWDummpZ)

**Comment by RayTrace082** [comment]
Released a new version a couple days ago, since I never managed to replicate this, is there any news on whether this has been fixed?

If there's still issues loading old worlds, do those issues also arise on a new world?

**Comment by juan-db** [comment]
I encountered the bug again in another save, but after updating the mod I was able to load into the world without crashing. I haven't encountered again the bug since.

**Comment by RayTrace082** [comment]
Gonna guess these issues got fixed due to the lack of posts, so closing the threads
