### ISSUE TITLE
Cage crashes when capturing some modded creatures

### ISSUE THREAD

**Issue by WabashCannon** [RayTrace082/untamedwilds#93]
Game crashes when cage fails to cast modded mob to ComplexMob

Attempting to capture a goblin from the goblin traders mod in a cage causes a game crash.

**Crash Log**
[log](https://pastebin.com/STF2XRvW)

**Version (please complete the following information):**
 - Minecraft version: 1.16.5
 - Version of the mod: 1.5.3
 - Additional mods: https://www.curseforge.com/minecraft/mc-mods/goblin-traders

**Comment by RayTrace082** [comment]
Of course, this is the mandatory "I forgot to disable a debug thing" crash. Expect another version sometime today
