### ISSUE TITLE
Critical error detected whilst generating Feature [minecraft:chance,minecraft:decorated,untamedwilds:burrow]

### ISSUE THREAD

**Issue by gglobensky** [RayTrace082/untamedwilds#95]
**Describe the bug**
Server crashed when flying around on homemade server

**Steps To Reproduce**
Seem to be related to Terraforged generation and untamed wilds burrow

**Crash Log**
https://pastebin.com/pKQjkv4n

**Version (please complete the following information):**
 - Minecraft version: 1.16.5
 - Version of the mod: 1.5.2 Alpha
 - Additional mods: Terraforged, Roadrunner - See crashlog for full modlist, I listed the most relevant I could think of.
 
 Thanks for the nice mobs!

**Comment by PhweeDev** [comment]
This also happens, TerraForged or not. on all 1.5.x versions

**Comment by RayTrace082** [comment]
I got this report after having done some small refactors in the Burrow class logic (which includes the code pointed by the log). Can't say if this issue has been fixed, but it *may* have been addressed in the latest version, any news?

**Comment by gglobensky** [comment]
I hadn't updated because the changelog didn't mention this bugfix. I will update and keep you posted!

**Comment by RayTrace082** [comment]
Gonna guess these issues got fixed due to the lack of posts, so closing the threads
